### ISSUE TITLE
Green and Red led not turning on in the GUI (ie, web page)

### ISSUE THREAD

**Issue by satfan52** [dl9sec/MFJ-993WWRC#2]
Hello again, 

I have connected the esp8266 module to logic analyzer and was able to see all the relevant pins of the ESP8266 turning on and off as I was pressing the corresponding buttons on the GUI. So that parts works fine for me.

I have tied D2 (Tune led) and D3 (High SWR led) pins of the ESP8266 first to ground and as it did not work to 3.3V,  hoping to see the green and red leds turning on/off on the GUI, but that did not happen.... I also tried pressing on the Tune button with D2  pin on the ESP8266 tied to ground but no success either. I also tried with the D2 pin tied to 3.3V but no luck either. 

How could I test this functionality ? or is there something wrong with the code ?

Thanks

**Comment by dl9sec** [comment]
The code is running very well on my D1, so the code should not be the problem. I did exactly the same tests as you did when I developed the firmware (the D1 with no FETs connected, signals 0V/3V3 directly to the pins). You should start the serial console to see the debug output of the ESP, maybe this will help you to see what happens...

**Comment by dl9sec** [comment]
btw.: I tested only with Firefox and Chrome. Could you try one of these browsers?

**Comment by satfan52** [comment]
Thanks. Will try the serial console.
